export class SizeConstants {
  static readonly FULL_WIDTH_PERCENT: string = '100%';
  static readonly FULL_HEIGHT_PERCENT: string = '100%';
  static readonly PERCENT_70 = '70%';
  static readonly PERCENT_80 = '80%';
  static readonly PERCENT_90 = '90%';
  static readonly PERCENT_50 = '50%';
  static readonly PAGE_SIDE_PADDING: number = 8;
  static readonly PAGE_HEADER_TOP_PADDING: number = 14;
  static readonly PAGE_CONTENT_BOTTOM_PADDING: number = 24;
  static readonly FLOATING_BUTTON_TOP_OFFSET: number = 18;
}
